"""First migrations

Revision ID: fe1ffdff296a
Revises: ad167da99f1a
Create Date: 2024-06-26 16:20:34.158990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe1ffdff296a'
down_revision: Union[str, None] = 'ad167da99f1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('options_type', postgresql.ENUM('smile', 'score', 'custom', name='optionstype'), nullable=False))
    op.drop_column('questions', 'options_types')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('options_types', postgresql.ENUM('smile', 'score', 'custom', name='optionstype'), autoincrement=False, nullable=False))
    op.drop_column('questions', 'options_type')
    # ### end Alembic commands ###
